# 启用本插件的世界
# 如果为空 则不启用本插件
enabled_world:
  - world # 示例：默认的主世界名
  - resource # 示例：资源世界名
  #- your_world_name

# 模式选择，1 或 2
# 模式1：如果某作物垂直方向多于1个作物，垂直方向的所有作物都将减产
# 模式2：只允许露天环境的作物生长，作物上方不能存在任何方块（较为激进的限制）
mode: 2
# 模式1的提示语
mode1_notice_message: "§b[农业系统] §a受垂直方向上§b{number1}个§a其它作物影响 所有作物生长速度将减缓为§b{number2}分之1"
# 模式2的提示语
mode2_notice_message: "§b[农业系统] §a该作物不在露天环境下 将不会生长 请移除上方所有的遮挡方块"
# 两条提示间隔 避免刷屏 单位：秒
notice_interval: 6